meta_product_name: "toFuture"
meta_title: "toFuture - Invest in change"
meta_description: "A sustainable investing platform focused on matching sustainable products with investors"
meta_image: "banner.jpg" # should exist in `app/assets/images/`
